- basic-operators.lua
- basic-types.lua
- samplecode.alc
there's a comment about the purpose of the tokens table, as well as a minor style change & a fix for the indentation in samplecode.alc
> comment; style fixes

- base-env.lua
- cotuple.lua
- metalanguage.lua
- reducer-utils.lua
> fix: Rename env_handler to accept_with_env and move out of metalang

- cotuple.lua
> fix: cotuple: Fix wrong variable usage

- base-env.lua
- cotuple.lua
- testfile.alc
> feat: Add cotuple flow operative

- terms.lua
Tries to add prop and prim logic to terms.lua
> add prop/prim

- terms-generators.lua
- terms.lua
- test-terms.lua
- Refactor terms to use the generators
- Add tests
> feat: Add term generators

- terms.lua
- test-terms.lua
terms: add value.number,number_type, typed.literal, inferrable.typed
terms: remove separate arginfo record type
> more terms!

- environment.lua
- metalanguage.lua
- terms-generators.lua
- terms.lua
> feat: Add more foreign types

- format-adapter.lua
- format.lua
is this acceptably bodged @bootstrap-prime
> format: bodge longstring like string

- derivers.lua
- terms-generators.lua
they cause a lot of warnings still, and i don't yet know how to communicate the way terms-generators works to the annotation language
> Add annotations

- alicorn-expressions.lua
- base-env.lua
- evaluator.lua
- runtest.lua
- terms.lua
- testfile.alc
> expressions: merge checked and inferred handling, pass target along

- .gitignore
- alicorn-expressions.lua
- base-env.lua
- environment.lua
- evaluator.lua
- flake.lock
- flake.nix
- format-adapter.lua
- runtest.lua
- terms.lua
- test-derive-pretty-print.lua
- test-terms.lua
Fixing the terms tests, fixing committed formatting, adding pre-commit hooks to encourage committing correctly formatted code.
> fix term tests and format, pre-commit hooks

- alicorn-expressions.lua
- derivers.lua
- flake.nix
- pretty-printable-trait.lua
- pretty-printer.lua
- terms-generators.lua
- test-derive-pretty-print.lua
- test-pretty-print.lua
- test-traits.lua
- testfile.alc
- traits.lua
> implement a new pretty printer to make debugging easier

- alicorn-expressions.lua
- base-env.lua
- environment.lua
- evaluator.lua
- internals-interface.lua
- pretty-printer.lua
- runtest.lua
- terms-generators.lua
- terms.lua
- testfile.alc
Various improvements in substitution, better debugging by attaching anchors to some terms, arrays in testfile.alc are now immutable, new operative to constrain types
> array-fixes

- base-env.lua
- evaluator.lua
- terms.lua
- testfile.alc
> Make forall / inferrable.pi work

- alicorn-expressions.lua
- base-env.lua
- environment.lua
- evaluator.lua
- terms.lua
- test-eval.lua
- test-fitsinto.lua
- test-syntax-to-terms-to-eval.lua
- testfile.alc
> Strip qtype

- pretty-printer.lua
- terms.lua
makes it not die of recursion
also fixes printing tables generally
> Fix simple table printing

- flake.nix
- format.lua
- test.lua
cleans up the commit list of #75
> Merge progress from main branch

- alicorn-expressions.lua
- base-env.lua
~~CI is mad about lua style in terms.lua which I didn't change :/~~
> base-env, alicorn-expressions: add lua_operative type for primitive lua operatives

- alicorn-expressions.lua
- base-env.lua
- environment.lua
- evaluator.lua
- metalanguage.lua
- runtest.lua
- terms-generators.lua
- terms-pretty.lua
- terms.lua
- testfile.alc
- types/binding.lua
- types/inferrable.lua
- types/typed.lua
- types/value.lua
tracking progress of effects
this pr is based ontop of #95 and #96 so a) make sure to check those out and b) if they're not yet merged, use this link to see the changes particular to this pr <https://github.com/AstroSnail/Alicorn0/compare/dde4f4cacf0cb861201bdc17e8448bb0104ccb68...feature/effects>
> Effects progress

- alicorn-expressions.lua
- environment.lua
- evaluator.lua
- terms-pretty.lua
- terms.lua
- test-syntax-to-terms-to-eval.lua
- testfile.alc
you didn't tell me you were going to merge >:(
(<3)
> Massive refactor (2)

- base-env.lua
- evaluator.lua
- testfile.alc
draft because i only tested for regression (doesn't seem to break existing code), haven't tested usage. help making example code will be welcome
> Add support for omitting colon and type in a lambda param

- alicorn-expressions.lua
- base-env.lua
- environment.lua
- evaluator.lua
- terms.lua
- testfile.alc
- types/binding.lua
- types/inferrable.lua
- types/typed.lua
open wanted this feature in main, so i cherry-picked it out and merged it with progress-since-then on main
> plumb some extra effectful stuff

- alicorn-utils.lua
- base-env.lua
- metalanguage.lua
- pretty-printer.lua
- reducer-utils.lua
- terms-generators.lua
- testfile.alc
> Replace { ... } and select("#", ...) with table.pack(...)

- evaluator.lua
- runtest.lua
- terms.lua
> [!NOTE]  
> You may want to review the following stack with [ReviewStack](<https://reviewstack.dev/Fundament-Software/Alicorn0/pull/124>):
* #127 (1 commits)
* #126 (11 commits)
* #125 (2 commits)
* __->__ #124 (5 commits)
pulled out of Open's original `feature/program-support` work. mostly minor; should be set to merge pretty quickly.
> program support prerequsites

- .luarc.json
- evaluator.lua
- flake.nix
- runtest.lua
- terms.lua
> [!NOTE]  
> You may want to review the following stack with [ReviewStack](<https://reviewstack.dev/Fundament-Software/Alicorn0/pull/125>):
* #127 (1 commits)
* #126 (11 commits)
* __->__ #125 (2 commits)
* #124 (5 commits) (soft dependency)
it's useful sometimes to be able to run LuaLS from the CLI.
these commits don't semantically depend on `feature/program-support-prereqs` if you'd like to integrate them first. i just have them here because i needed to run type checks for later work on top of that branch.
> unbreak LuaLS from the CLI

- .luarc.json
- alicorn-expressions.lua
- alicorn-utils.lua
- base-env.lua
- environment.lua
- evaluator.lua
- flake.nix
- format-adapter.lua
- format.lua
- metalanguage.lua
- runtest.lua
- syntax-schema.lua
- terms.lua
- test-format-adapter.lua
- test.lua
- testlanguage.lua
- unformatter.lua
> [!NOTE]  
> You may want to review the following stack with [ReviewStack](<https://reviewstack.dev/Fundament-Software/Alicorn0/pull/126>):
* #127 (1 commits)
* __->__ #126 (11 commits)
* #125 (2 commits) (soft dependency)
* #124 (5 commits)
mostly @aiverson's work, with me adding better support for `end_anchor`. the results would really benefit from @bootstrap-prime's in-progress work on propagating anchors through inferred terms.
just a soft dependency on `feature/lua-language-server`, since i was using it to (attempt to) type-check my changes here. these commits can trivially be moved to …
> progress tracking

- .luarc.json
- alicorn-expressions.lua
- alicorn-utils.lua
- base-env.lua
- environment.lua
- evaluator.lua
- flake.nix
- format-adapter.lua
- format.lua
- metalanguage.lua
- runtest.lua
- syntax-schema.lua
- terms.lua
- test-format-adapter.lua
- test.lua
- testfile.alc
- testlanguage.lua
- unformatter.lua
> [!NOTE]  
> You may want to review the following stack with [ReviewStack](<https://reviewstack.dev/Fundament-Software/Alicorn0/pull/127>):
* __->__ #127 (1 commits)
* #126 (11 commits) (soft dependency)
* #125 (2 commits) (soft dependency)
* #124 (5 commits)
@aiverson's work.
soft dependency on `feature/progress-tracking`, since it was being used to test how evaluation was going.
> effectful program support

- testfile.alc
> [!NOTE]  
> You may want to review the following stack with [ReviewStack](<https://reviewstack.dev/Fundament-Software/Alicorn0/pull/128>):
* __->__ #128 (3 commits)
* #126 (11 commits) (soft dependency)
* #125 (2 commits) (soft dependency)
* #124 (5 commits)
@aiverson's work. pulled out from <https://github.com/Fundament-Software/Alicorn0/pull/127>.
> easier host array creation

- .gitignore
- .vscode/launch.json
- runtest.lua
@ErikMcClure this might conflict with your Windows setup? if so, `//.vscode/launch.json` can be dropped.
> support Second Local Lua Debugger

- flake.lock
- flake.nix
main is pointing at ancient nixos-23.11.
> flake: bump lockfile, update nixos input to nixos-24.11

- alicorn-expressions.lua
- alicorn-utils.lua
- base-env.lua
- derivers.lua
- environment.lua
- evaluator.lua
- format.lua
- runtest.lua
- terms-gen-meta.lua
- terms-generators.lua
- terms-pretty.lua
- terms.lua
- traits.lua
This merges in hash-consing and adds a bit of jank to make it actually work with our debug info. This requires disabling our tracing mechanism for now until we decide to either let it through manually or what.
> Rescue impliciting

- .editorconfig
- .envrc
- .gitignore
- .lua-format
- .styluaignore
- REUSE.toml
- flake.nix
- nix/fe/fetchLitDeps/nixpkgs-package.nix
- nix/lu/luvi-prefix/nixpkgs-package.nix
- nix/lu/luvi/_patches/0001-CMake-non-internal-RPATH-cache-variables.patch
- nix/lu/luvi/_patches/0002-Respect-provided-CMAKE_INSTALL_RPATH.patch
- nix/lu/luvi/nixpkgs-package.nix
- nix/lu/luvit-lit/nixpkgs-package.nix
- nix/lu/luvit/nixpkgs-overlay.nix
- nix/lu/luvit/nixpkgs-package.nix
- nix/ma/makeLitPackage/nixpkgs-package.nix
- nix/wr/writeLuvi/nixpkgs-package.nix
- nix/wr/writeLuviBin/nixpkgs-package.nix
- nvim-site/README.md
- nvim-site/lua/treesitter-quickfix.lua
- nvim-site/queries/lua/refactored_functions.scm
- nvim-site/queries/lua/tail_calls.scm
please see individual commits & their descriptions.
> fix licensing for Nix & Neovim-specific source files

- evaluator.lua
- runtest.lua
> improve snapshots

- LICENSES/CC0-1.0.txt
Ran `reuse download --all` to fetch this
> CC0-1.0.txt: init

- alicorn-expressions.lua
- base-env.lua
- derivers.lua
- evaluator-types.lua
- evaluator.lua
- format.lua
- terms-generators.lua
- terms.lua
- test-derive-eq.lua
- test-derive-pretty-print.lua
- test-eval.lua
- test-syntax-to-terms-to-eval.lua
- types/constraintcause.lua
- types/edgenotif.lua
- types/flex_value.lua
- types/free.lua
- types/strict_value.lua
- types/stuck_value.lua
- types/typed.lua
- types/unanchored_inferrable.lua
and other commits while i was in the area. please review individual commits.
recreation of #179 on the new HEAD.
> terms: introduce `terms_gen.builtin_integer`

- terms-generators.lua
- terms.lua
> terms: finish refactoring flex machinery

- build.rs
- lib.rs
- libs/sandbox.lua
Sandboxes alicorn so it can safely execute untrusted code.
> Add a sandbox to alicorn

- test.lua
requesting review from @bootstrap-prime
> tests: use less globals for LuaUnit
