- terms.lua
- test-terms.lua
- Remains as a variant of neutral_value
- Tests and helper functions got reworked
> fix: Remove free variant from values

- evaluator.lua
- test-terms.lua
Some tests were broken during the terms-generator refactor so CI was failing.
Brought back some code which was removed (I think accidentally) during the terms-generator refactor
> test-terms: fix/remove broken tests

- format.lua
- test.lua
comments no longer unconditionally consume whitespace characters to allow intermediate empty newlines
> fix: comment character consumption behavior

- alicorn-expressions.lua
- metalanguage.lua
Second arg to function passed to metalanguage.reducer was always unused.
> metalanguage: remove extra unused arg from reducers

- metalanguage.lua
- testlanguage.lua
unpack is deprecated since 5.2
> Function unpack was moved into the table library and therefore must be called as table.unpack.
> *: unpack -> table.unpack

- flake.lock
- flake.nix
Needed to add nixpkgs-unstable input for stylua as a recent release is required for `call_parentheses = Input` from d66e087cf24198c3d9f1daadabb233f039477974
> flake: add stylua formatting check and add stylua to shell

- derivers.lua
- test-derive-pretty-print.lua
Before:
```
typed_let {
expr = typed_prim_intrinsic {
source = typed_literal {
literal_value = value_prim {
primitive_value = return function(a, b) return a - b end
}
}
}
body = typed_tuple_elim {
subject = typed_application {
f = typed_bound_variable {
index = 1
}
arg = typed_prim_tuple_cons {
elements = [typed_literal {
literal_value = value_prim {
primitive_value = 5
}
}, typed_literal {
literal_value = value_prim {
primitive_value = 1
}
}]
}
}
length = 1
body = typed_application {
f = typed_bound_variable {
index = 1
}
arg = typed_prim_tuple_cons {
elements = [typed_bound_variable {
index = 2
}, typed_literal {
literal_value = value_prim {
primitive_value = 3
}
}]
}
}
}
}
```
After:
```
typed_let{
expr = typed_prim_intrinsic(typed_literal(value_prim("return function(a, b) return a - b …
```
> derivers: special case pretty_print for single element to simplify common terms

- derivers.lua
- evaluator.lua
- terms.lua
- test-derive-pretty-print.lua
Missing value. prefix for qtype in evaluator and more detailed error messages for fitsinto failing and function arg/param type mismatch
Includes cherry-pick of #43
> Fix for boxing qtype and debugging improvements

- terms-generators.lua
Requested earlier by @aiverson
> terms-generators: log more info when an invalid value is passed to a record constructor

- alicorn-expressions.lua
- base-env.lua
This doesn't fix the issue running testfile.alc but it should make the error less confusing
> expressions,base-env: improve diagnostics for prim_func_type and collect_tuple

- format.lua
- test.lua
Anchor position wasn't being correctly tracked because Cb() pulls from the *outermost named capture*. so all of the named captures in nested captures, such as lists and strings, were not updated on newlines and so anchors were unreliable. the grammar can now handle this properly and transmit context. it should be significantly easier to transmit additional context (if needed) in the future.
there's now a more general property test for validating outputs of the format, and some new tests for specific edge cases.
comments and longstrings now normalize their indentation levels to the indentation level of the parent.
> fix: anchor position now correctly tracked

- alicorn-expressions.lua
- evaluator.lua
- metalanguage.lua
- runtest.lua
- testfile.alc
This is very messy right now due to the NYI for primitive operative apply failures converting them to lua errors.
https://github.com/Fundament-Software/Alicorn0/blob/e332cfb6a94242c0f41e953ff1b86965e63b03e1/alicorn-expressions.lua#L408-L415
I am not sure how to fix this.
> metalanguage: augment reducer errors with anchors

- terms-generators.lua
tostring(records/enums/foreigns) from terms-generator produced types now shows a description of the type so the error for an incorrect parameter type says what type it is supposed to be instead of pretty-printing the entire term type.
> terms-generators: better error for incorrect parameter types

- base-env.lua
- reducer-utils.lua
- testfile.alc
- add lambda_single for cases where we need single
- change lambda_implicit to require single
- does not affect lambda_curry (it still requires double parens for a singleton tuple param)
> Make lambda always take tuple params

- alicorn-expressions.lua
- alicorn-utils.lua
- metalanguage.lua
There were two bugs:
- facing an empty block, the block reducer returns a nil lastval followed by the environment. the match function rolls this into a table and then unpacks it, which dropped the environment. this is fixed by making the match function more resilient to nils.
- after that, the nil violates the contract that the block reducer returns an inferrable term. this is fixed by initializing lastval to an empty tuple_cons.
> Fix empty blocks

- evaluator.lua
- tests/basic-annotated.alc
This fixes the below test case (which will be added to "should fail" once the test harness actually works) where we were not constraining the annotated return value of a lambda due to not enforcing a constraint between a left edge and a right edge.
> Fix left call right call

- alicorn-expressions.lua
- alicorn-utils.lua
- base-env.lua
- environment.lua
- evaluator.lua
This comments out all our U.tag nonsense and makes alicorn go literally 100 times faster. Some of these U.tags are likely not needed anymore, because of debug-trace can be more precise. Some of them may still be needed in certain cases, and can be uncommented in that case.
> Remove all debug tags so we can go zoom

- alicorn-expressions.lua
- base-env.lua
- environment.lua
- evaluator.lua
and a bunch of refactoring around speculation, particularly:
- moving out code unnecessarily running in speculation
- hopefully establishing a process for debugging errors that go through speculation
speculating expressions containing operatives is still TODO
> Speculate expressions again

- flake.nix
i wrote this patch during the last time i was hacking on Alicorn, but hadn't submitted it then.
> remove potentially harmful `LUA_PATH` override

- .github/workflows/nix-flake-check.yml
GitHub removed the caching API it relies on. There's a successor but it's not free. Not caching for now is acceptable and that's what was happening already.
> nix-flake-check: remove magic nix cache

- flake.nix
Check runs reuse lint on the src dir and fails if it finds any issues.
Assuming reuse is sticking around it'd be good to check compliance in CI.
> flake: add reuse-lint flake check

- alicorn-expressions.lua
- alicorn-utils.lua
- evaluator.lua
- format.lua
- prelude.alc
- pretty-printer.lua
- terms-generators.lua
- terms.lua
- tests/host-if.alc
This lets us run alicorn without debuginfo for use in safe rust contexts (and anywhere else that doesn't have debug exposed for whatever reason). Feather already had the relevant changes done to it's layout.alc file, I confirmed that it now works when passed a fully safe lua context with this change active.
> Unglue debuginfo

- REUSE.toml
A part of #163 that I think is still very relevant. I'd encourage reading the linked SPDX documentation.
> license `REUSE.toml` in a way compliant with the SPDX specification

- .github/workflows/nix-flake-check.yml
Logs get cut off otherwise making finding failures slightly more annoying.
> nix-flake-check: pass -L to nix flake check

- test-terms.lua
The existing tests don't work.
Removed ancient metavariable test which was for the old metavariable impl. ~~Commented the level/star tests since the terms they use are missing but not sure if still needed.~~ Removed after confirming these are obsolete.
> test-terms: swap to very simple empty tuple test

- .github/workflows/nix-flake-check.yml
Without this check both `on: push` and `on: pull_request` fire. Still allows PR to fire checks for external repos.
> nix-flake-check: don't run checks twice on PRs in fundament repo

- .github/workflows/nix-flake-status.sh
Trying to get per-attr status working for external PRs. Currently failing check suite creation, see https://github.com/Fundament-Software/Alicorn0/pull/187 for an example of failing CI.
> nix-flake-status: fall back to commit status if check suite fails

- glsl-prelude.alc
- lib.rs
This also changes the glsl-prelude to emit wgpu types, at least for now. This means if we re-introduce the GLSL tests, they will need to be changed to operate on wgpu types instead of glsl ones.
> Change rust API to load preludes

- getopt.lua
- lua-ext.lua
- runtest.lua
i would like to be able to introduce options in `runtest.lua`, even just for debugging, without having to come up with really bad short option names for them
> getopt, runtest: support long options

- base-env.lua
- prelude.alc
mainly these commits just port the remaining host arithmetic operations. wanted to remove `alicorn_expressions.host_applicative()` entirely but @aiverson said to wait on that.
> avoid `alicorn_expressions.host_applicative()`

- Cargo.toml
- lib.rs
mlua has a new version that gets rid of all the annoying lifetimes. This is a breaking change, so this updates alicorn to keep it in sync with feather.
> bump lua version to sync with feather
